logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:h2:file:./simpledb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create #update table
      ddl-auto: update
  h2:
    console: 
      enabled: true 
      path: /h2

#Congig app TODO Обязательно сменить ключ
app:
  jwt: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  exp: 86400000