logging:
  level:
    org:
      springframework:
        security: DEBUG
        
springdoc:
  api-docs:
    enabled: true
    path: /api-docs

spring:
  application:
    name: TaskManager-doc
  datasource:
    url: jdbc:h2:file:./simpledocdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create 
  
  h2:
    console: 
      enabled: true 
      path: /h2

app:
  jwt: necessary-to-change-the-key-for-jwt-doc
  exp: 86400000