springdoc:
  api-docs:
    enabled: false
    path: /api-docs

spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:h2:file:./simpledb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

#Congig app TODO Обязательно сменить ключ
app:
  jwt: necessary-to-change-the-key-for-jwt
  exp: 86400000